version: "3.8"

services:

  frontend:
    container_name: iot_frontend
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start